-- 1. Create Tables
CREATE TABLE IF NOT EXISTS gallery_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    src TEXT NOT NULL,
    caption TEXT,
    category TEXT
);

CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT,
    date TEXT,
    author TEXT,
    comments INTEGER DEFAULT 0,
    excerpt TEXT,
    content TEXT,
    image TEXT
);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT,
    price TEXT,
    lessons INTEGER,
    students INTEGER,
    rating FLOAT,
    instructor_name TEXT,
    description TEXT,
    explanation TEXT,
    uniqueness TEXT[],
    image TEXT
);

-- 2. Enable RLS (Row Level Security)
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

-- 3. Create Public Select Policies
CREATE POLICY "Allow public select on gallery" ON gallery_images FOR SELECT USING (true);
CREATE POLICY "Allow public select on blog" ON blog_posts FOR SELECT USING (true);
CREATE POLICY "Allow public select on courses" ON courses FOR SELECT USING (true);

-- 4. Create Admin All Policies (Requires Authentication)
CREATE POLICY "Allow auth admin all on gallery" ON gallery_images FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow auth admin all on blog" ON blog_posts FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow auth admin all on courses" ON courses FOR ALL TO authenticated USING (true);

-- 5. Storage Buckets (Run these commands or create manually in Supabase Dashboard)
-- Insert into storage.buckets (id, name, public) VALUES ('gallery_uploads', 'gallery_uploads', true);
-- Insert into storage.buckets (id, name, public) VALUES ('blog_uploads', 'blog_uploads', true);
-- Insert into storage.buckets (id, name, public) VALUES ('course_uploads', 'course_uploads', true);

-- 6. Storage Policies (Allow public read, authenticated write)
-- NOTE: Policy creation for storage depends on your Supabase version, 
-- but generally you need to allow INSERT/UPDATE/DELETE for 'authenticated' users
-- and SELECT for 'public'.