export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as FeatureCards } from './FeatureCards';
export { default as AboutSection } from './AboutSection';
export { default as StatsSection } from './StatsSection';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as PopularCourses } from './PopularCourses';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as AboutPage } from './AboutPage';
export { default as CoursesPage } from './CoursesPage';
export { default as BlogPage } from './BlogPage';
export { default as SingleBlogPostPage } from './SingleBlogPostPage';
export { default as AdmissionForm } from './AdmissionForm';
export { default as GalleryManagement } from './GalleryManagement';
export { default as SuperAdminDashboard } from './SuperAdminDashboard';
export { default as SettingsManagement } from './SettingsManagement';
export { default as CourseCard } from './CourseCard';
export type { Course } from './CourseCard';
export { default as ContactPage } from './ContactPage';
export { default as CourseDetailPage } from './CourseDetailPage';
export { default as LoginPage } from './LoginPage';
export { default as Notification } from './Notification';
export type { NotificationType } from './Notification';